#7. Pinheiro  - Implemente um programa que desenhe um "pinheiro" na tela, similar ao abaixo.
print("       x")
print("      XXX")
print("     XXXXX")
print("    XXXXXXX")
print("   XXXXXXXXX")
print("  XXXXXXXXXXX")
print(" XXXXXXXXXXXXX")
print("XXXXXXXXXXXXXXX")
print("       XX")
print("       XX")
print("      XXXX")
